# See https://docs.platform.sh/user_guide/reference/routes-yaml.html

"http://{default}/":
    type: upstream
    upstream: "app:http"

"http://www.{default}/":
    type: redirect
    to: "http://{default}/"
